/**
 * google-ads-mcp-server: an open-source MCP server for the Google Ads API.
 * Copyright 2026 GetMCPAds. https://www.getmcpads.com
 * SPDX-License-Identifier: Apache-2.0
 */
// ============================================
// GOOGLE ADS API v23 METRIC CATALOG
// Complete catalog of 120+ Google Ads metrics
// Based on Google Ads API v23 GAQL metric fields
// ============================================

import {
  GoogleAdsMetricDefinition,
  GoogleAdsMetricCategory,
  GoogleAdsResourceType,
} from "./types.js";

// ============================================
// CORE PERFORMANCE METRICS
// ============================================

const CORE_METRICS: GoogleAdsMetricDefinition[] = [
  {
    key: "impressions",
    name: "Impressions",
    description: "Total number of times your ads were shown on a search results page or website.",
    category: "core",
    format: "number",
    apiField: "metrics.impressions",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
  {
    key: "clicks",
    name: "Clicks",
    description: "Total number of clicks on your ads.",
    category: "core",
    format: "number",
    apiField: "metrics.clicks",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
  {
    key: "ctr",
    name: "CTR",
    description: "Click-through rate, the ratio of clicks to impressions.",
    category: "core",
    format: "percentage",
    apiField: "metrics.ctr",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
  {
    key: "interactions",
    name: "Interactions",
    description: "Number of interactions, including clicks, swipes, and video views depending on ad type.",
    category: "core",
    format: "number",
    apiField: "metrics.interactions",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
  {
    key: "interactionRate",
    name: "Interaction Rate",
    description: "The ratio of interactions to impressions for your ad.",
    category: "core",
    format: "percentage",
    apiField: "metrics.interaction_rate",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
  {
    key: "engagementRate",
    name: "Engagement Rate",
    description: "The rate of engagements (expansions of lightbox ads) divided by impressions.",
    category: "core",
    format: "percentage",
    apiField: "metrics.engagement_rate",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "geographic_view",
      "user_location_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "video",
      "customer",
    ],
  },
  {
    key: "reach",
    name: "Reach",
    description: "Estimated number of unique users who saw your ad at least once.",
    category: "core",
    format: "number",
    apiField: "metrics.reach",
    type: "api",
    compatibleResources: ["campaign", "ad_group", "ad_group_ad", "customer"],
  },
  {
    key: "frequency",
    name: "Frequency",
    description: "Average number of times a unique user saw your ad.",
    category: "core",
    format: "ratio",
    apiField: "metrics.frequency",
    type: "api",
    compatibleResources: ["campaign", "ad_group", "ad_group_ad", "customer"],
  },
  {
    key: "absoluteTopImpressionPercentage",
    name: "Absolute Top Impression %",
    description: "Percentage of ad impressions shown as the very first ad above organic results.",
    category: "core",
    format: "percentage",
    apiField: "metrics.absolute_top_impression_percentage",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "ad_group_criterion",
      "customer",
    ],
  },
  {
    key: "topImpressionPercentage",
    name: "Top Impression %",
    description: "Percentage of ad impressions shown anywhere above organic search results.",
    category: "core",
    format: "percentage",
    apiField: "metrics.top_impression_percentage",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "ad_group_criterion",
      "customer",
    ],
  },
  {
    key: "interactionEventTypes",
    name: "Interaction Event Types",
    description: "The types of interactions that are counted as interactions for this campaign type.",
    category: "core",
    format: "string",
    apiField: "metrics.interaction_event_types",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "customer",
    ],
  },
];

// ============================================
// SPEND / COST METRICS
// ============================================

const SPEND_METRICS: GoogleAdsMetricDefinition[] = [
  {
    key: "costMicros",
    name: "Cost",
    description: "Total cost of all clicks and interactions in micro-currency units.",
    category: "spend",
    format: "micro_currency",
    apiField: "metrics.cost_micros",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
  {
    key: "averageCpc",
    name: "Avg. CPC",
    description: "Average cost-per-click, the total cost divided by total clicks.",
    category: "spend",
    format: "micro_currency",
    apiField: "metrics.average_cpc",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
  {
    key: "averageCpm",
    name: "Avg. CPM",
    description: "Average cost per one thousand impressions.",
    category: "spend",
    format: "micro_currency",
    apiField: "metrics.average_cpm",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
  {
    key: "averageCost",
    name: "Avg. Cost",
    description: "Average amount paid per interaction.",
    category: "spend",
    format: "micro_currency",
    apiField: "metrics.average_cost",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
  {
    key: "averageCpe",
    name: "Avg. CPE",
    description: "Average cost per engagement (lightbox ad interactions).",
    category: "spend",
    format: "micro_currency",
    apiField: "metrics.average_cpe",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "geographic_view",
      "user_location_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "video",
      "customer",
    ],
  },
  {
    key: "averageCpv",
    name: "Avg. CPV",
    description: "Average cost per video view.",
    category: "spend",
    format: "micro_currency",
    apiField: "metrics.trueview_average_cpv",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "geographic_view",
      "user_location_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "video",
      "customer",
    ],
  },
  {
    key: "costPerCurrentModelAttributedConversion",
    name: "Cost / Current Model Conversion",
    description: "Cost per conversion using the current attribution model.",
    category: "spend",
    format: "micro_currency",
    apiField: "metrics.cost_per_current_model_attributed_conversion",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "customer",
    ],
  },
];

// ============================================
// CONVERSION METRICS
// ============================================

const CONVERSION_METRICS: GoogleAdsMetricDefinition[] = [
  {
    key: "conversions",
    name: "Conversions",
    description: "Total number of conversions from conversion actions included in the Conversions column.",
    category: "conversion",
    format: "number",
    apiField: "metrics.conversions",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
  {
    key: "conversionsValue",
    name: "Conversions Value",
    description: "Total value of conversions included in the Conversions column.",
    category: "conversion",
    format: "currency",
    apiField: "metrics.conversions_value",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
  {
    key: "costPerConversion",
    name: "Cost / Conversion",
    description: "Average cost per conversion.",
    category: "conversion",
    format: "micro_currency",
    apiField: "metrics.cost_per_conversion",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
  {
    key: "conversionsFromInteractionsRate",
    name: "Conversion Rate (Interaction)",
    description: "Conversions from interactions divided by the number of ad interactions.",
    category: "conversion",
    format: "percentage",
    apiField: "metrics.conversions_from_interactions_rate",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
  {
    key: "conversionsValuePerCost",
    name: "Conversions Value / Cost",
    description: "The value of conversions divided by the cost of ad interactions.",
    category: "conversion",
    format: "ratio",
    apiField: "metrics.conversions_value_per_cost",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
  {
    key: "allConversions",
    name: "All Conversions",
    description: "Total number of all conversions, including those not included in the Conversions column.",
    category: "conversion",
    format: "number",
    apiField: "metrics.all_conversions",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
  {
    key: "allConversionsValue",
    name: "All Conversions Value",
    description: "Total value of all conversions, including those not in the Conversions column.",
    category: "conversion",
    format: "currency",
    apiField: "metrics.all_conversions_value",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
  {
    key: "costPerAllConversions",
    name: "Cost / All Conversions",
    description: "Average cost per all conversions.",
    category: "conversion",
    format: "micro_currency",
    apiField: "metrics.cost_per_all_conversions",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
  {
    key: "allConversionsFromInteractionsRate",
    name: "All Conversions Rate (Interaction)",
    description: "All conversions from interactions divided by the number of ad interactions.",
    category: "conversion",
    format: "percentage",
    apiField: "metrics.all_conversions_from_interactions_rate",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
  {
    key: "allConversionsValuePerCost",
    name: "All Conversions Value / Cost",
    description: "The value of all conversions divided by the cost of ad interactions.",
    category: "conversion",
    format: "ratio",
    apiField: "metrics.all_conversions_value_per_cost",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
  {
    key: "viewThroughConversions",
    name: "View-Through Conversions",
    description: "Conversions from when a user saw but did not click your ad.",
    category: "conversion",
    format: "number",
    apiField: "metrics.view_through_conversions",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
  {
    key: "crossDeviceConversions",
    name: "Cross-Device Conversions",
    description: "Conversions where the user interacted on one device and converted on another.",
    category: "conversion",
    format: "number",
    apiField: "metrics.cross_device_conversions",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
  {
    key: "currentModelAttributedConversions",
    name: "Current Model Conversions",
    description: "Conversions attributed using the current attribution model for the conversion action.",
    category: "conversion",
    format: "number",
    apiField: "metrics.current_model_attributed_conversions",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "customer",
    ],
  },
  {
    key: "currentModelAttributedConversionsValue",
    name: "Current Model Conversions Value",
    description: "Value of conversions attributed using the current attribution model.",
    category: "conversion",
    format: "currency",
    apiField: "metrics.current_model_attributed_conversions_value",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "customer",
    ],
  },
  {
    key: "conversionsFromInteractionsValuePerInteraction",
    name: "Conv. Value / Interaction",
    description: "Value of conversions from interactions divided by total interactions.",
    category: "conversion",
    format: "currency",
    apiField: "metrics.conversions_from_interactions_value_per_interaction",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "customer",
    ],
  },
  {
    key: "valuePerAllConversions",
    name: "Value / All Conversions",
    description: "The value of all conversions divided by the number of all conversions.",
    category: "conversion",
    format: "currency",
    apiField: "metrics.value_per_all_conversions",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
  {
    key: "valuePerConversionApi",
    name: "Value / Conversion",
    description: "The value of conversions divided by the number of conversions.",
    category: "conversion",
    format: "currency",
    apiField: "metrics.value_per_conversion",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
  {
    key: "valuePerCurrentModelAttributedConversion",
    name: "Value / Current Model Conversion",
    description: "Value of current model attributed conversions divided by current model conversions.",
    category: "conversion",
    format: "currency",
    apiField: "metrics.value_per_current_model_attributed_conversion",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "customer",
    ],
  },
  {
    key: "allConversionsFromClickToCall",
    name: "All Conv. from Click to Call",
    description: "Number of phone call conversions from click-to-call ads.",
    category: "conversion",
    format: "number",
    apiField: "metrics.all_conversions_from_click_to_call",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "customer",
    ],
  },
  {
    key: "allConversionsFromDirections",
    name: "All Conv. from Directions",
    description: "Number of direction-getting conversions from local ads.",
    category: "conversion",
    format: "number",
    apiField: "metrics.all_conversions_from_directions",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "customer",
    ],
  },
  {
    key: "allConversionsFromMenu",
    name: "All Conv. from Menu",
    description: "Number of menu-viewing conversions from local ads.",
    category: "conversion",
    format: "number",
    apiField: "metrics.all_conversions_from_menu",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "customer",
    ],
  },
  {
    key: "allConversionsFromOrder",
    name: "All Conv. from Order",
    description: "Number of order conversions from local ads.",
    category: "conversion",
    format: "number",
    apiField: "metrics.all_conversions_from_order",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "customer",
    ],
  },
  {
    key: "allConversionsFromStoreVisit",
    name: "All Conv. from Store Visit",
    description: "Number of estimated store visit conversions.",
    category: "conversion",
    format: "number",
    apiField: "metrics.all_conversions_from_store_visit",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "customer",
    ],
  },
  {
    key: "allConversionsFromStoreWebsite",
    name: "All Conv. from Store Website",
    description: "Number of store website conversions from local ads.",
    category: "conversion",
    format: "number",
    apiField: "metrics.all_conversions_from_store_website",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "customer",
    ],
  },
  // --- Conversion Date Attribution Metrics ---
  // These metrics attribute conversions to the DATE THE CONVERSION OCCURRED,
  // NOT the date of the click/impression. Standard metrics (conversions, conversions_value)
  // attribute to click date. These are useful for finance/analytics reporting.
  {
    key: "conversionsByConversionDate",
    name: "Conversions (Conv. Time)",
    description: "Conversions attributed to the date the conversion occurred, not the click date. Useful for understanding actual conversion timing and reporting lag.",
    category: "conversion",
    format: "number",
    apiField: "metrics.conversions_by_conversion_date",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
  {
    key: "conversionsValueByConversionDate",
    name: "Conversions Value (Conv. Time)",
    description: "Revenue attributed to the date the conversion occurred, not the click date. Note: cannot be divided by cost for ROAS since cost is attributed to spend date.",
    category: "conversion",
    format: "currency",
    apiField: "metrics.conversions_value_by_conversion_date",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
  {
    key: "allConversionsByConversionDate",
    name: "All Conversions (Conv. Time)",
    description: "All conversions (including secondary) attributed to the date the conversion occurred, not the click date.",
    category: "conversion",
    format: "number",
    apiField: "metrics.all_conversions_by_conversion_date",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
  {
    key: "allConversionsValueByConversionDate",
    name: "All Conversions Value (Conv. Time)",
    description: "Total value of all conversions (including secondary) attributed to the date the conversion occurred, not the click date.",
    category: "conversion",
    format: "currency",
    apiField: "metrics.all_conversions_value_by_conversion_date",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
];

// ============================================
// IMPRESSION SHARE METRICS
// ============================================

const IMPRESSION_SHARE_METRICS: GoogleAdsMetricDefinition[] = [
  {
    key: "searchImpressionShare",
    name: "Search Impression Share",
    description: "Percentage of eligible search impressions your ads received.",
    category: "impression_share",
    format: "percentage",
    apiField: "metrics.search_impression_share",
    type: "api",
    compatibleResources: ["campaign", "ad_group", "keyword_view", "ad_group_criterion"],
    incompatibleSegments: ["segments.click_type", "segments.ad_destination_type"],
  },
  {
    key: "searchBudgetLostImpressionShare",
    name: "Search Lost IS (Budget)",
    description: "Estimated percentage of search impressions lost due to insufficient budget.",
    category: "impression_share",
    format: "percentage",
    apiField: "metrics.search_budget_lost_impression_share",
    type: "api",
    compatibleResources: ["campaign"],
    incompatibleSegments: ["segments.click_type", "segments.ad_destination_type"],
  },
  {
    key: "searchRankLostImpressionShare",
    name: "Search Lost IS (Rank)",
    description: "Estimated percentage of search impressions lost due to poor Ad Rank.",
    category: "impression_share",
    format: "percentage",
    apiField: "metrics.search_rank_lost_impression_share",
    type: "api",
    compatibleResources: ["campaign", "ad_group", "keyword_view", "ad_group_criterion"],
    incompatibleSegments: ["segments.click_type", "segments.ad_destination_type"],
  },
  {
    key: "searchTopImpressionShare",
    name: "Search Top IS",
    description: "Percentage of eligible top-of-page search impressions your ads received.",
    category: "impression_share",
    format: "percentage",
    apiField: "metrics.search_top_impression_share",
    type: "api",
    compatibleResources: ["campaign", "ad_group", "keyword_view", "ad_group_criterion"],
    incompatibleSegments: ["segments.click_type", "segments.ad_destination_type"],
  },
  {
    key: "searchAbsoluteTopImpressionShare",
    name: "Search Abs. Top IS",
    description: "Percentage of eligible absolute top search impressions your ads received.",
    category: "impression_share",
    format: "percentage",
    apiField: "metrics.search_absolute_top_impression_share",
    type: "api",
    compatibleResources: ["campaign", "ad_group", "keyword_view", "ad_group_criterion"],
    incompatibleSegments: ["segments.click_type", "segments.ad_destination_type"],
  },
  {
    key: "searchExactMatchImpressionShare",
    name: "Search Exact Match IS",
    description: "Percentage of eligible impressions received for searches that exactly matched your keywords.",
    category: "impression_share",
    format: "percentage",
    apiField: "metrics.search_exact_match_impression_share",
    type: "api",
    compatibleResources: ["campaign", "ad_group", "keyword_view", "ad_group_criterion"],
    incompatibleSegments: ["segments.click_type", "segments.ad_destination_type"],
  },
  {
    key: "searchBudgetLostAbsoluteTopImpressionShare",
    name: "Search Lost Abs. Top IS (Budget)",
    description: "Estimated percentage of absolute top search impressions lost due to budget.",
    category: "impression_share",
    format: "percentage",
    apiField: "metrics.search_budget_lost_absolute_top_impression_share",
    type: "api",
    compatibleResources: ["campaign"],
    incompatibleSegments: ["segments.click_type", "segments.ad_destination_type"],
  },
  {
    key: "searchBudgetLostTopImpressionShare",
    name: "Search Lost Top IS (Budget)",
    description: "Estimated percentage of top search impressions lost due to budget.",
    category: "impression_share",
    format: "percentage",
    apiField: "metrics.search_budget_lost_top_impression_share",
    type: "api",
    compatibleResources: ["campaign"],
    incompatibleSegments: ["segments.click_type", "segments.ad_destination_type"],
  },
  {
    key: "searchRankLostAbsoluteTopImpressionShare",
    name: "Search Lost Abs. Top IS (Rank)",
    description: "Estimated percentage of absolute top search impressions lost due to Ad Rank.",
    category: "impression_share",
    format: "percentage",
    apiField: "metrics.search_rank_lost_absolute_top_impression_share",
    type: "api",
    compatibleResources: ["campaign", "ad_group", "keyword_view", "ad_group_criterion"],
    incompatibleSegments: ["segments.click_type", "segments.ad_destination_type"],
  },
  {
    key: "searchRankLostTopImpressionShare",
    name: "Search Lost Top IS (Rank)",
    description: "Estimated percentage of top search impressions lost due to Ad Rank.",
    category: "impression_share",
    format: "percentage",
    apiField: "metrics.search_rank_lost_top_impression_share",
    type: "api",
    compatibleResources: ["campaign", "ad_group", "keyword_view", "ad_group_criterion"],
    incompatibleSegments: ["segments.click_type", "segments.ad_destination_type"],
  },
  {
    key: "contentImpressionShare",
    name: "Content Impression Share",
    description: "Percentage of eligible Display Network impressions your ads received.",
    category: "impression_share",
    format: "percentage",
    apiField: "metrics.content_impression_share",
    type: "api",
    compatibleResources: ["campaign", "ad_group"],
    incompatibleSegments: ["segments.click_type", "segments.ad_destination_type"],
  },
  {
    key: "contentBudgetLostImpressionShare",
    name: "Content Lost IS (Budget)",
    description: "Estimated percentage of Display Network impressions lost due to budget.",
    category: "impression_share",
    format: "percentage",
    apiField: "metrics.content_budget_lost_impression_share",
    type: "api",
    compatibleResources: ["campaign"],
    incompatibleSegments: ["segments.click_type", "segments.ad_destination_type"],
  },
  {
    key: "contentRankLostImpressionShare",
    name: "Content Lost IS (Rank)",
    description: "Estimated percentage of Display Network impressions lost due to Ad Rank.",
    category: "impression_share",
    format: "percentage",
    apiField: "metrics.content_rank_lost_impression_share",
    type: "api",
    compatibleResources: ["campaign", "ad_group"],
    incompatibleSegments: ["segments.click_type", "segments.ad_destination_type"],
  },
];

// ============================================
// VIDEO METRICS
// ============================================

const VIDEO_METRICS: GoogleAdsMetricDefinition[] = [
  {
    key: "videoViews",
    name: "Video Views",
    description: "Total number of times your video ads were viewed.",
    category: "video",
    format: "number",
    apiField: "metrics.video_trueview_views",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "geographic_view",
      "user_location_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "video",
      "customer",
    ],
  },
  {
    key: "videoViewRate",
    name: "Video View Rate",
    description: "The rate of video views relative to impressions.",
    category: "video",
    format: "percentage",
    apiField: "metrics.video_trueview_view_rate",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "geographic_view",
      "user_location_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "video",
      "customer",
    ],
  },
  {
    key: "videoQuartileP25Rate",
    name: "Video Played to 25%",
    description: "Percentage of impressions where the video played to 25% of its length.",
    category: "video",
    format: "percentage",
    apiField: "metrics.video_quartile_p25_rate",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "geographic_view",
      "user_location_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "video",
      "customer",
    ],
  },
  {
    key: "videoQuartileP50Rate",
    name: "Video Played to 50%",
    description: "Percentage of impressions where the video played to 50% of its length.",
    category: "video",
    format: "percentage",
    apiField: "metrics.video_quartile_p50_rate",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "geographic_view",
      "user_location_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "video",
      "customer",
    ],
  },
  {
    key: "videoQuartileP75Rate",
    name: "Video Played to 75%",
    description: "Percentage of impressions where the video played to 75% of its length.",
    category: "video",
    format: "percentage",
    apiField: "metrics.video_quartile_p75_rate",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "geographic_view",
      "user_location_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "video",
      "customer",
    ],
  },
  {
    key: "videoQuartileP100Rate",
    name: "Video Played to 100%",
    description: "Percentage of impressions where the video played to 100% of its length.",
    category: "video",
    format: "percentage",
    apiField: "metrics.video_quartile_p100_rate",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "geographic_view",
      "user_location_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "video",
      "customer",
    ],
  },
  {
    key: "engagements",
    name: "Engagements",
    description: "Number of engagements, such as clicks on lightbox ads or video interactions.",
    category: "video",
    format: "number",
    apiField: "metrics.engagements",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "geographic_view",
      "user_location_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "video",
      "customer",
    ],
  },
  {
    key: "averageVideoViewDuration",
    name: "Avg. Video View Duration",
    description: "Average duration in seconds of all video views.",
    category: "video",
    format: "duration",
    apiField: "metrics.average_video_watch_time_duration_millis",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "video",
      "customer",
    ],
  },
  {
    key: "videoDuration",
    name: "Video Duration",
    description: "Average duration in milliseconds of the video ad.",
    category: "video",
    format: "duration",
    apiField: "metrics.video_duration_millis",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "video",
    ],
  },
  {
    key: "videoViewsP25",
    name: "Video Views (25%)",
    description: "Number of times your video played to 25% of its length.",
    category: "video",
    format: "number",
    apiField: "metrics.video_quartile_p25",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "video",
      "customer",
    ],
  },
  {
    key: "videoViewsP50",
    name: "Video Views (50%)",
    description: "Number of times your video played to 50% of its length.",
    category: "video",
    format: "number",
    apiField: "metrics.video_quartile_p50",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "video",
      "customer",
    ],
  },
  {
    key: "videoViewsP75",
    name: "Video Views (75%)",
    description: "Number of times your video played to 75% of its length.",
    category: "video",
    format: "number",
    apiField: "metrics.video_quartile_p75",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "video",
      "customer",
    ],
  },
  {
    key: "videoViewsP100",
    name: "Video Views (100%)",
    description: "Number of times your video played to 100% of its length.",
    category: "video",
    format: "number",
    apiField: "metrics.video_quartile_p100",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "video",
      "customer",
    ],
  },
  {
    key: "averageTimeOnSite",
    name: "Avg. Time on Site",
    description: "Average duration of all sessions on the website from ad clicks, in seconds.",
    category: "video",
    format: "duration",
    apiField: "metrics.average_time_on_site",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "customer",
    ],
  },
  {
    key: "bounceRate",
    name: "Bounce Rate",
    description: "Percentage of clicks where the user only visited a single page on your site.",
    category: "video",
    format: "percentage",
    apiField: "metrics.bounce_rate",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "customer",
    ],
  },
  {
    key: "percentNewVisitors",
    name: "% New Visitors",
    description: "Percentage of first-time sessions from ad clicks.",
    category: "video",
    format: "percentage",
    apiField: "metrics.percent_new_visitors",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "customer",
    ],
  },
  {
    key: "trueViews",
    name: "TrueViews",
    description: "Number of TrueView video ad views. A view is counted when someone watches 30 seconds of the video (or the entire ad if shorter) or interacts with the ad. Equivalent to Video Views for YouTube campaigns.",
    category: "video",
    format: "number",
    apiField: "metrics.video_trueview_views",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "geographic_view",
      "user_location_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "video",
      "customer",
    ],
  },
  {
    key: "trueViewRate",
    name: "TrueView Rate",
    description: "TrueView rate: the number of views divided by impressions. Shows how often people chose to watch your video ad. Use segments.ad_network_type to break down by In-Stream vs In-Feed.",
    category: "video",
    format: "percentage",
    apiField: "metrics.video_trueview_view_rate",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "geographic_view",
      "user_location_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "video",
      "customer",
    ],
  },
  {
    key: "trueViewRateInStream",
    name: "TrueView Rate (In-Stream)",
    description: "TrueView view rate for In-Stream ads (skippable pre-roll, mid-roll). Add segments.ad_network_type = YOUTUBE_WATCH dimension to your query for accurate In-Stream breakdown.",
    category: "video",
    format: "percentage",
    apiField: "metrics.video_trueview_view_rate",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "geographic_view",
      "user_location_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "video",
      "customer",
    ],
  },
  {
    key: "trueViewRateInFeed",
    name: "TrueView Rate (In-Feed)",
    description: "TrueView view rate for In-Feed/Discovery ads. Add segments.ad_network_type = YOUTUBE_SEARCH dimension to your query for accurate In-Feed breakdown.",
    category: "video",
    format: "percentage",
    apiField: "metrics.video_trueview_view_rate",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "geographic_view",
      "user_location_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "video",
      "customer",
    ],
  },
  {
    key: "trueViewShorts",
    name: "TrueView (Shorts)",
    description: "TrueView views from YouTube Shorts placement. Add segments.ad_network_type dimension and filter for Shorts format to isolate Shorts-specific views.",
    category: "video",
    format: "number",
    apiField: "metrics.video_trueview_views",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "geographic_view",
      "user_location_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "video",
      "customer",
    ],
  },
];

// ============================================
// ENGAGEMENT METRICS (Gmail & Display)
// ============================================

const ENGAGEMENT_METRICS: GoogleAdsMetricDefinition[] = [
  {
    key: "gmailForwards",
    name: "Gmail Forwards",
    description: "Number of times your Gmail ad was forwarded to someone else.",
    category: "engagement",
    format: "number",
    apiField: "metrics.gmail_forwards",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "customer",
    ],
  },
  {
    key: "gmailSaves",
    name: "Gmail Saves",
    description: "Number of times someone saved your Gmail ad to their inbox.",
    category: "engagement",
    format: "number",
    apiField: "metrics.gmail_saves",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "customer",
    ],
  },
  {
    key: "gmailSecondaryClicks",
    name: "Gmail Secondary Clicks",
    description: "Number of clicks to the landing page on the expanded state of your Gmail ad.",
    category: "engagement",
    format: "number",
    apiField: "metrics.gmail_secondary_clicks",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "customer",
    ],
  },
  {
    key: "phoneCalls",
    name: "Phone Calls",
    description: "Number of offline phone calls initiated from call extensions or call-only ads.",
    category: "engagement",
    format: "number",
    apiField: "metrics.phone_calls",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "customer",
    ],
  },
  {
    key: "phoneImpressions",
    name: "Phone Impressions",
    description: "Number of times your phone number was shown with your ad.",
    category: "engagement",
    format: "number",
    apiField: "metrics.phone_impressions",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "customer",
    ],
  },
  {
    key: "phoneThroughRate",
    name: "Phone Through Rate",
    description: "Number of phone calls divided by number of phone impressions.",
    category: "engagement",
    format: "percentage",
    apiField: "metrics.phone_through_rate",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "customer",
    ],
  },
];

// ============================================
// QUALITY SCORE METRICS
// ============================================

const QUALITY_METRICS: GoogleAdsMetricDefinition[] = [
  {
    key: "qualityScore",
    name: "Quality Score",
    description: "Current quality score of the keyword on a 1-10 scale.",
    category: "quality",
    format: "number",
    apiField: "ad_group_criterion.quality_info.quality_score",
    type: "api",
    compatibleResources: ["keyword_view", "ad_group_criterion"],
  },
  {
    key: "historicalQualityScore",
    name: "Historical Quality Score",
    description: "Historical quality score at the time of the last report snapshot.",
    category: "quality",
    format: "number",
    apiField: "metrics.historical_quality_score",
    type: "api",
    compatibleResources: ["keyword_view", "ad_group_criterion"],
  },
  {
    key: "historicalCreativeQualityScore",
    name: "Historical Creative Quality",
    description: "Historical ad relevance quality component.",
    category: "quality",
    format: "enum",
    apiField: "metrics.historical_creative_quality_score",
    type: "api",
    compatibleResources: ["keyword_view", "ad_group_criterion"],
  },
  {
    key: "historicalLandingPageQualityScore",
    name: "Historical Landing Page Quality",
    description: "Historical landing page experience quality component.",
    category: "quality",
    format: "enum",
    apiField: "metrics.historical_landing_page_quality_score",
    type: "api",
    compatibleResources: ["keyword_view", "ad_group_criterion"],
  },
  {
    key: "historicalSearchPredictedCtr",
    name: "Historical Expected CTR",
    description: "Historical expected click-through rate quality component.",
    category: "quality",
    format: "enum",
    apiField: "metrics.historical_search_predicted_ctr",
    type: "api",
    compatibleResources: ["keyword_view", "ad_group_criterion"],
  },
];

// ============================================
// SHOPPING METRICS
// Shopping uses standard metrics but on shopping_performance_view resource
// ============================================

const SHOPPING_METRICS: GoogleAdsMetricDefinition[] = [
  {
    key: "shoppingImpressions",
    name: "Shopping Impressions",
    description: "Number of times your Shopping ads were shown.",
    category: "shopping",
    format: "number",
    apiField: "metrics.impressions",
    type: "api",
    compatibleResources: ["shopping_performance_view"],
  },
  {
    key: "shoppingClicks",
    name: "Shopping Clicks",
    description: "Number of clicks on your Shopping ads.",
    category: "shopping",
    format: "number",
    apiField: "metrics.clicks",
    type: "api",
    compatibleResources: ["shopping_performance_view"],
  },
  {
    key: "shoppingCostMicros",
    name: "Shopping Cost",
    description: "Total cost of Shopping ad clicks in micro-currency.",
    category: "shopping",
    format: "micro_currency",
    apiField: "metrics.cost_micros",
    type: "api",
    compatibleResources: ["shopping_performance_view"],
  },
  {
    key: "shoppingConversions",
    name: "Shopping Conversions",
    description: "Number of conversions from Shopping ads.",
    category: "shopping",
    format: "number",
    apiField: "metrics.conversions",
    type: "api",
    compatibleResources: ["shopping_performance_view"],
  },
  {
    key: "shoppingConversionsValue",
    name: "Shopping Conversions Value",
    description: "Total value of conversions from Shopping ads.",
    category: "shopping",
    format: "currency",
    apiField: "metrics.conversions_value",
    type: "api",
    compatibleResources: ["shopping_performance_view"],
  },
  {
    key: "shoppingCtr",
    name: "Shopping CTR",
    description: "Click-through rate for Shopping ads.",
    category: "shopping",
    format: "percentage",
    apiField: "metrics.ctr",
    type: "api",
    compatibleResources: ["shopping_performance_view"],
  },
  {
    key: "shoppingAverageCpc",
    name: "Shopping Avg. CPC",
    description: "Average cost-per-click for Shopping ads.",
    category: "shopping",
    format: "micro_currency",
    apiField: "metrics.average_cpc",
    type: "api",
    compatibleResources: ["shopping_performance_view"],
  },
  {
    key: "shoppingAllConversions",
    name: "Shopping All Conversions",
    description: "All conversions from Shopping ads including cross-device.",
    category: "shopping",
    format: "number",
    apiField: "metrics.all_conversions",
    type: "api",
    compatibleResources: ["shopping_performance_view"],
  },
  {
    key: "shoppingAllConversionsValue",
    name: "Shopping All Conv. Value",
    description: "Total value of all conversions from Shopping ads.",
    category: "shopping",
    format: "currency",
    apiField: "metrics.all_conversions_value",
    type: "api",
    compatibleResources: ["shopping_performance_view"],
  },
  {
    key: "shoppingCostPerConversion",
    name: "Shopping Cost / Conversion",
    description: "Average cost per conversion for Shopping ads.",
    category: "shopping",
    format: "micro_currency",
    apiField: "metrics.cost_per_conversion",
    type: "api",
    compatibleResources: ["shopping_performance_view"],
  },
];

// ============================================
// COMPETITIVE / AUCTION INSIGHT METRICS
// Note: Auction insights are accessed via a special service,
// not standard GAQL queries. These represent the fields returned.
// ============================================

const COMPETITIVE_METRICS: GoogleAdsMetricDefinition[] = [
  {
    key: "auctionInsightSearchImpressionShare",
    name: "Auction Insight: Search IS",
    description: "Your search impression share compared to competitors in auction insights.",
    category: "competitive",
    format: "percentage",
    apiField: "metrics.auction_insight_search_impression_share",
    type: "api",
    compatibleResources: ["campaign", "ad_group", "keyword_view", "ad_group_criterion"],
  },
  {
    key: "auctionInsightSearchOverlapRate",
    name: "Auction Insight: Overlap Rate",
    description: "How often a competitor's ad received an impression when your ad also received one.",
    category: "competitive",
    format: "percentage",
    apiField: "metrics.auction_insight_search_overlap_rate",
    type: "api",
    compatibleResources: ["campaign", "ad_group", "keyword_view", "ad_group_criterion"],
  },
  {
    key: "auctionInsightSearchPositionAboveRate",
    name: "Auction Insight: Position Above Rate",
    description: "How often a competitor's ad was shown above yours in the same auction.",
    category: "competitive",
    format: "percentage",
    apiField: "metrics.auction_insight_search_position_above_rate",
    type: "api",
    compatibleResources: ["campaign", "ad_group", "keyword_view", "ad_group_criterion"],
  },
  {
    key: "auctionInsightSearchTopOfPageRate",
    name: "Auction Insight: Top of Page Rate",
    description: "How often a competitor's ad appeared at the top of the page.",
    category: "competitive",
    format: "percentage",
    apiField: "metrics.auction_insight_search_top_of_page_rate",
    type: "api",
    compatibleResources: ["campaign", "ad_group", "keyword_view", "ad_group_criterion"],
  },
  {
    key: "auctionInsightSearchAbsoluteTopOfPageRate",
    name: "Auction Insight: Abs. Top Rate",
    description: "How often a competitor's ad appeared at the absolute top of the page.",
    category: "competitive",
    format: "percentage",
    apiField: "metrics.auction_insight_search_absolute_top_of_page_rate",
    type: "api",
    compatibleResources: ["campaign", "ad_group", "keyword_view", "ad_group_criterion"],
  },
  {
    key: "auctionInsightSearchOutrankingShare",
    name: "Auction Insight: Outranking Share",
    description: "Percentage of auctions where your ad ranked higher than a competitor or showed when they did not.",
    category: "competitive",
    format: "percentage",
    apiField: "metrics.auction_insight_search_outranking_share",
    type: "api",
    compatibleResources: ["campaign", "ad_group", "keyword_view", "ad_group_criterion"],
  },
];

// ============================================
// INVALID TRAFFIC METRICS
// ============================================

const INVALID_TRAFFIC_METRICS: GoogleAdsMetricDefinition[] = [
  {
    key: "invalidClicks",
    name: "Invalid Clicks",
    description: "Number of clicks Google considers illegitimate and does not charge for.",
    category: "invalid_traffic",
    format: "number",
    apiField: "metrics.invalid_clicks",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "ad_group_criterion",
      "customer",
    ],
  },
  {
    key: "invalidClickRate",
    name: "Invalid Click Rate",
    description: "Percentage of total clicks that are filtered as invalid.",
    category: "invalid_traffic",
    format: "percentage",
    apiField: "metrics.invalid_click_rate",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "ad_group_criterion",
      "customer",
    ],
  },
];

// ============================================
// ACTIVE VIEW (VIEWABILITY) METRICS
// ============================================

const ACTIVE_VIEW_METRICS: GoogleAdsMetricDefinition[] = [
  {
    key: "activeViewCpm",
    name: "Active View CPM",
    description: "Average cost per thousand viewable impressions.",
    category: "core",
    format: "micro_currency",
    apiField: "metrics.active_view_cpm",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "customer",
    ],
  },
  {
    key: "activeViewCtr",
    name: "Active View CTR",
    description: "Clicks divided by viewable impressions.",
    category: "core",
    format: "percentage",
    apiField: "metrics.active_view_ctr",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "customer",
    ],
  },
  {
    key: "activeViewImpressions",
    name: "Active View Impressions",
    description: "Number of impressions that met Active View viewability criteria.",
    category: "core",
    format: "number",
    apiField: "metrics.active_view_impressions",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "customer",
    ],
  },
  {
    key: "activeViewMeasurability",
    name: "Active View Measurability",
    description: "Ratio of impressions that could be measured by Active View.",
    category: "core",
    format: "percentage",
    apiField: "metrics.active_view_measurability",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "customer",
    ],
  },
  {
    key: "activeViewMeasurableImpressions",
    name: "Active View Measurable Impressions",
    description: "Number of impressions that were measurable by Active View.",
    category: "core",
    format: "number",
    apiField: "metrics.active_view_measurable_impressions",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "customer",
    ],
  },
  {
    key: "activeViewMeasurableCostMicros",
    name: "Active View Measurable Cost",
    description: "Cost of impressions that were measurable by Active View.",
    category: "core",
    format: "micro_currency",
    apiField: "metrics.active_view_measurable_cost_micros",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "customer",
    ],
  },
  {
    key: "activeViewViewability",
    name: "Active View Viewability",
    description: "Percentage of measurable impressions that were actually viewable.",
    category: "core",
    format: "percentage",
    apiField: "metrics.active_view_viewability",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "customer",
    ],
  },
];

// ============================================
// CROSS-DEVICE METRICS
// (cross_device_conversions is already in CONVERSION_METRICS)
// These are additional cross-device specific metrics
// ============================================

const CROSS_DEVICE_METRICS: GoogleAdsMetricDefinition[] = [
  {
    key: "crossDeviceConversionsValueMicros",
    name: "Cross-Device Conv. Value",
    description: "Value of conversions where the user interacted on one device and converted on another.",
    category: "cross_device",
    format: "currency",
    apiField: "metrics.cross_device_conversions_value",
    type: "api",
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "customer",
    ],
  },
];

// ============================================
// CALCULATED METRICS (derived client-side)
// These are computed client-side from raw API data
// ============================================

const CALCULATED_METRICS: GoogleAdsMetricDefinition[] = [
  {
    key: "roas",
    name: "ROAS",
    description: "Return on ad spend: conversions value divided by cost.",
    category: "calculated",
    format: "ratio",
    apiField: "",
    type: "calculated",
    formula: "metrics.conversions_value / (metrics.cost_micros / 1_000_000)",
    dependencies: ["conversionsValue", "costMicros"],
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "customer",
    ],
  },
  {
    key: "allConversionsRoas",
    name: "All Conversions ROAS",
    description: "Return on ad spend for all conversions: all conversions value divided by cost.",
    category: "calculated",
    format: "ratio",
    apiField: "",
    type: "calculated",
    formula: "metrics.all_conversions_value / (metrics.cost_micros / 1_000_000)",
    dependencies: ["allConversionsValue", "costMicros"],
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "customer",
    ],
  },
  {
    key: "valuePerConversion",
    name: "Value per Conversion",
    description: "Average value per conversion: conversions value divided by number of conversions.",
    category: "calculated",
    format: "currency",
    apiField: "",
    type: "calculated",
    formula: "metrics.conversions_value / metrics.conversions",
    dependencies: ["conversionsValue", "conversions"],
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "customer",
    ],
  },
  {
    key: "allConversionsValuePerConversion",
    name: "Value per All Conversion",
    description: "Average value per all conversions: all conversions value divided by all conversions.",
    category: "calculated",
    format: "currency",
    apiField: "",
    type: "calculated",
    formula: "metrics.all_conversions_value / metrics.all_conversions",
    dependencies: ["allConversionsValue", "allConversions"],
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "customer",
    ],
  },
  {
    key: "hookRate",
    name: "Hook Rate",
    description: "Proxy for video hook rate using the 25% quartile view rate.",
    category: "calculated",
    format: "percentage",
    apiField: "",
    type: "calculated",
    formula: "metrics.video_quartile_p25_rate",
    dependencies: ["videoQuartileP25Rate"],
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "video",
    ],
  },
  {
    key: "holdRate",
    name: "Hold Rate",
    description: "Ratio of 50% video views to 25% video views, indicating mid-video retention.",
    category: "calculated",
    format: "percentage",
    apiField: "",
    type: "calculated",
    formula: "(metrics.video_quartile_p50_rate / metrics.video_quartile_p25_rate) * 100",
    dependencies: ["videoQuartileP50Rate", "videoQuartileP25Rate"],
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "video",
    ],
  },
  {
    key: "completionRate",
    name: "Completion Rate",
    description: "Ratio of 100% video views to 25% video views, indicating full-video retention.",
    category: "calculated",
    format: "percentage",
    apiField: "",
    type: "calculated",
    formula: "(metrics.video_quartile_p100_rate / metrics.video_quartile_p25_rate) * 100",
    dependencies: ["videoQuartileP100Rate", "videoQuartileP25Rate"],
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "video",
    ],
  },
  {
    key: "impressionShareLostTotal",
    name: "Search IS Lost (Total)",
    description: "Total search impression share lost, combining budget and rank lost shares.",
    category: "calculated",
    format: "percentage",
    apiField: "",
    type: "calculated",
    formula: "metrics.search_budget_lost_impression_share + metrics.search_rank_lost_impression_share",
    dependencies: ["searchBudgetLostImpressionShare", "searchRankLostImpressionShare"],
    compatibleResources: ["campaign"],
  },
  {
    key: "spendShare",
    name: "Spend Share",
    description: "Percentage of total spend allocated to this entity, computed across all rows.",
    category: "calculated",
    format: "percentage",
    apiField: "",
    type: "calculated",
    formula: "(metrics.cost_micros / total_cost_micros) * 100",
    dependencies: ["costMicros"],
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "customer",
    ],
  },
  {
    key: "costPerConversionDollars",
    name: "Cost / Conversion ($)",
    description: "Cost per conversion in standard currency (converted from micros).",
    category: "calculated",
    format: "currency",
    apiField: "",
    type: "calculated",
    formula: "metrics.cost_micros / metrics.conversions / 1_000_000",
    dependencies: ["costMicros", "conversions"],
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "customer",
    ],
  },
  {
    key: "costDollars",
    name: "Cost ($)",
    description: "Total cost in standard currency (converted from micros).",
    category: "calculated",
    format: "currency",
    apiField: "",
    type: "calculated",
    formula: "metrics.cost_micros / 1_000_000",
    dependencies: ["costMicros"],
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "detail_placement_view",
      "topic_view",
      "campaign_audience_view",
      "ad_group_audience_view",
      "ad_group_criterion",
      "asset_group",
      "video",
      "customer",
    ],
  },
  {
    key: "averageCpcDollars",
    name: "Avg. CPC ($)",
    description: "Average cost-per-click in standard currency (converted from micros).",
    category: "calculated",
    format: "currency",
    apiField: "",
    type: "calculated",
    formula: "metrics.average_cpc / 1_000_000",
    dependencies: ["averageCpc"],
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "customer",
    ],
  },
  {
    key: "averageCpmDollars",
    name: "Avg. CPM ($)",
    description: "Average cost per thousand impressions in standard currency (converted from micros).",
    category: "calculated",
    format: "currency",
    apiField: "",
    type: "calculated",
    formula: "metrics.average_cpm / 1_000_000",
    dependencies: ["averageCpm"],
    compatibleResources: [
      "campaign",
      "ad_group",
      "ad_group_ad",
      "keyword_view",
      "search_term_view",
      "shopping_performance_view",
      "geographic_view",
      "user_location_view",
      "landing_page_view",
      "customer",
    ],
  },
];

// ============================================
// COMBINE ALL METRICS
// ============================================

export const GOOGLE_ADS_METRIC_CATALOG: GoogleAdsMetricDefinition[] = [
  ...CORE_METRICS,
  ...SPEND_METRICS,
  ...CONVERSION_METRICS,
  ...IMPRESSION_SHARE_METRICS,
  ...VIDEO_METRICS,
  ...ENGAGEMENT_METRICS,
  ...QUALITY_METRICS,
  ...SHOPPING_METRICS,
  ...COMPETITIVE_METRICS,
  ...INVALID_TRAFFIC_METRICS,
  ...ACTIVE_VIEW_METRICS,
  ...CROSS_DEVICE_METRICS,
  ...CALCULATED_METRICS,
];

// ============================================
// HELPER FUNCTIONS
// ============================================

/**
 * Get all Google Ads metrics
 */
export function getGoogleAdsMetrics(): GoogleAdsMetricDefinition[] {
  return GOOGLE_ADS_METRIC_CATALOG;
}

/**
 * Get metric definition by key
 */
export function getGoogleAdsMetricByKey(
  key: string
): GoogleAdsMetricDefinition | undefined {
  return GOOGLE_ADS_METRIC_CATALOG.find((m) => m.key === key);
}

/**
 * Get metrics by category
 */
export function getGoogleAdsMetricsByCategory(
  category: GoogleAdsMetricCategory
): GoogleAdsMetricDefinition[] {
  return GOOGLE_ADS_METRIC_CATALOG.filter((m) => m.category === category);
}

/**
 * Get API-only metrics (optionally filtered by keys)
 */
export function getGoogleAdsApiMetrics(
  keys?: string[]
): GoogleAdsMetricDefinition[] {
  const apiMetrics = GOOGLE_ADS_METRIC_CATALOG.filter(
    (m) => m.type === "api"
  );
  if (!keys || keys.length === 0) return apiMetrics;
  return apiMetrics.filter((m) => keys.includes(m.key));
}

/**
 * Get calculated-only metrics (optionally filtered by keys)
 */
export function getGoogleAdsCalculatedMetrics(
  keys?: string[]
): GoogleAdsMetricDefinition[] {
  const calcMetrics = GOOGLE_ADS_METRIC_CATALOG.filter(
    (m) => m.type === "calculated"
  );
  if (!keys || keys.length === 0) return calcMetrics;
  return calcMetrics.filter((m) => keys.includes(m.key));
}

/**
 * Convert metric keys to GAQL API fields.
 * For calculated metrics, includes the API fields of their dependencies.
 */
export function googleAdsMetricKeysToApiFields(keys: string[]): string[] {
  const apiFields = new Set<string>();

  for (const key of keys) {
    const metric = getGoogleAdsMetricByKey(key);
    if (!metric) continue;

    if (metric.type === "api" && metric.apiField) {
      apiFields.add(metric.apiField);
    } else if (metric.type === "calculated" && metric.dependencies) {
      // For calculated metrics, resolve the dependencies to their API fields
      for (const depKey of metric.dependencies) {
        const depMetric = getGoogleAdsMetricByKey(depKey);
        if (depMetric?.type === "api" && depMetric.apiField) {
          apiFields.add(depMetric.apiField);
        }
      }
    }
  }

  return Array.from(apiFields);
}

/**
 * Get metric definition by API field
 */
export function getGoogleAdsMetricByApiField(
  apiField: string
): GoogleAdsMetricDefinition | undefined {
  return GOOGLE_ADS_METRIC_CATALOG.find(
    (m) => m.apiField === apiField && m.type === "api"
  );
}

/**
 * Get all metric categories present in the catalog
 */
export function getGoogleAdsMetricCategories(): GoogleAdsMetricCategory[] {
  return [...new Set(GOOGLE_ADS_METRIC_CATALOG.map((m) => m.category))];
}

/**
 * Get dependencies for calculated metrics
 */
export function getGoogleAdsMetricDependencies(keys: string[]): string[] {
  const dependencies = new Set<string>();

  for (const key of keys) {
    const metric = getGoogleAdsMetricByKey(key);
    if (metric?.type === "calculated" && metric.dependencies) {
      for (const dep of metric.dependencies) {
        dependencies.add(dep);
      }
    }
  }

  return Array.from(dependencies);
}

/**
 * Get count of metrics by category
 */
export function getGoogleAdsMetricCountByCategory(): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const metric of GOOGLE_ADS_METRIC_CATALOG) {
    counts[metric.category] = (counts[metric.category] || 0) + 1;
  }
  return counts;
}

/**
 * Get metrics compatible with a specific resource type
 */
export function getGoogleAdsMetricsForResource(
  resource: GoogleAdsResourceType
): GoogleAdsMetricDefinition[] {
  return GOOGLE_ADS_METRIC_CATALOG.filter(
    (m) =>
      !m.compatibleResources || m.compatibleResources.includes(resource)
  );
}

export default GOOGLE_ADS_METRIC_CATALOG;
